# Generated by Django 4.2.1 on 2023-07-17 09:35

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorOccupationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=12)),
                ("photo_of_link", models.ImageField(upload_to="image_of_link")),
                ("social_media_name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("Address", models.CharField(blank=True, default=None, max_length=300)),
                (
                    "Occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.authoroccupationmodel",
                    ),
                ),
                (
                    "social_media_links",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.socialmediamodel",
                    ),
                ),
            ],
        ),
    ]
