# Generated by Django 4.2.1 on 2023-07-18 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authormodel",
            name="Occupation",
        ),
    ]
