# Generated by Django 4.2.1 on 2023-07-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0002_remove_authormodel_occupation"),
    ]

    operations = [
        migrations.AddField(
            model_name="authoroccupationmodel",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="author.authormodel",
            ),
        ),
    ]
