# Generated by Django 4.2.1 on 2023-07-18 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0003_authoroccupationmodel_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authoroccupationmodel",
            name="author",
        ),
    ]
