# Generated by Django 4.2.1 on 2023-07-18 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0004_remove_authoroccupationmodel_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorModel",
        ),
    ]
