# Generated by Django 4.2.1 on 2023-07-18 16:24

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0005_delete_authormodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("Address", models.CharField(blank=True, default=None, max_length=300)),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.authoroccupationmodel",
                    ),
                ),
                (
                    "social_media_links",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.socialmediamodel",
                    ),
                ),
            ],
        ),
    ]
