# Generated by Django 4.2.1 on 2023-07-18 17:03

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0007_alter_socialmediamodel_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=900)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="images_of_author_posts"),
                ),
                (
                    "video",
                    models.FileField(blank=True, upload_to="videos_of_author_posts"),
                ),
                ("blog_text", models.TextField(default="None")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.authormodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=500)),
                (
                    "photo_of_category",
                    models.ImageField(upload_to="images_of_categories"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("subject", models.CharField(max_length=400)),
                ("text", models.TextField(default="None")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrdinaryUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_score", models.IntegerField()),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.blogpostmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=1000)),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.ordinaryusermodel",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.blogpostmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="author.categorymodel"
            ),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="hashtag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="author.tagmodel"
            ),
        ),
    ]
